### ISSUE TITLE
App crash on stop.

### ISSUE THREAD

**Issue by kiritnim** [ananevam/react-native-play-audio#2]
Hi, 

All working good on both device. I Play the sound file well. but I want to stop it on button event. so I will put the code on button event.

**Play and Stop button different.** 

`
AudioPlayer.stop();`

**Error :** 

An instance 0x60000021a620 of class AVPlayerItem was deallocated while key value observers were still registered with it

**Comment by snoteboom** [comment]
Was this fixed?
